name: cleaninggreenvillesc.com
favicon: null
layout_spectrum: 0.76434
typography_spectrum: 0.62119
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8f9194'
    - '#ffffff'
    - '#000000'
    - '#00ffff'
    - '#00ff00'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0
purpose: []
